### ISSUE TITLE
Mutlipass Configuration

### ISSUE THREAD

**Issue by Amacc** [Amacc/Kubernetes#2]
Hey @chrisstinemetz , I created this new repo so we can collab and tried to move over your commits to this but the branch shows the commits in my name, you should be a collab for this project so if you wanna delete the branch and create a pr to main so that your commits would be attributed to you that would be cool.

Once that PR gets created I wanna look at a couple of things. For the inventory script we can update the python script to implement this convention then you can create a yml file that can source the data on runtime, that way there will not be any need for an interim file.
https://docs.ansible.com/ansible/latest/dev_guide/developing_inventory.html

**Comment by ghost** [comment]
Sounds great. I will take a look at the convention you sent me. I'm looking forward to collaborating with you. This will be fun! Thanks

**Comment by ghost** [comment]
@Amacc  I am getting ready to make a PR. I was able to create a dynamic inventory based on the convention you shared. Let me know what you think. Here is a screenshot of it in action.

![image](https://user-images.githubusercontent.com/2374438/153790129-d7ed1818-27f8-40d6-8a82-a3f739d7ae7d.png)

**Comment by Amacc** [comment]
Closed with Merge of GH-4
